# docker run --rm --volume="$PWD:/srv/jekyll" -p 4000:4000 jekyll/jekyll:latest jekyll serve

version: "3.9"
services:
  jekyll-serve:
    image: jekyll/jekyll:latest
    volumes:
      - ".:/srv/jekyll"
    ports:
      - 4000:4000
    command: "jekyll serve"


